# Generated by Django 4.2.6 on 2023-11-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urunno', models.IntegerField()),
                ('ad', models.CharField(max_length=600)),
                ('fiyat', models.CharField(max_length=700)),
                ('stokdurumu', models.CharField(max_length=60)),
                ('acıklama', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Inceleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inceleme', models.CharField(max_length=1000)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inceleme', to='urunler.urunler')),
            ],
        ),
    ]
