# Generated by Django 4.2.6 on 2023-12-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_alter_inceleme_inceleme'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='profilresmi',
            field=models.CharField(default='', max_length=100),
        ),
    ]
