# Generated by Django 4.2.6 on 2023-12-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_urunler_profilresmi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urunler',
            old_name='profilresmi',
            new_name='urunResmi',
        ),
    ]
