# Generated by Django 4.2.6 on 2023-12-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_rename_profilresmi_urunler_urunresmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceleme',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.urunler'),
        ),
    ]
